### ISSUE TITLE
Feature request: Support Authorized Fetch on Mastodon instances

### ISSUE THREAD

**Issue by rodti** [citizenfx/fivem#3086]
### What happened?

'Unauthorized' error when trying to connect to Mastodon instance with Authorized Fetch enabled.

### Expected result

FiveM authorizes with Mastodon via API

### Reproduction steps

1. Set up FiveM server
2. Set up Mastodon account on instance with Authorized Fetch enabled (for example mas.to)
3. Enable connection to Mastodon in FiveM config
4. Received Unauthorised error when trying to connect to feed

### Importancy

Slight inconvenience

### Area(s)

FiveM, RedM

### Specific version(s)

Current

### Additional information

I'm the admin of a large Mastodon instance. We have a signifant number of FiveM users creating accounts on our instance so they can create a feed to their FiveM server.

As our instance has Authorized Fetch enabled, these users will get 'Unauthorised' errors in FiveM when they try to connect to the feed. This leads users to think their account has been limited in some way, when actually it is in good standing but their FiveM calls are being rejected due to the lack of any authorization details.

[Here's](https://forum.cfx.re/t/how-to-add-this/1242998/31) an example of a user having this issue.

More details about Authorized Fetch [here](https://docs.joinmastodon.org/admin/config/#authorized_fetch) and [here](https://hub.sunny.garden/2023/06/28/what-does-authorized_fetch-actually-do/).

Would it be possible to update ActiveActivityPubFeed.ts so it provides the required authentication details to work with Authorized Fetch? It should be a minor change but will make life better for a lot of confused FiveM users!

**Comment by Legacy-TacticalGamingInteractive** [comment]
@rodti is it specific to your instance or all of them due to issue on FiveM side?

**Comment by rodti** [comment]
> [@rodti](https://github.com/rodti) is it specific to your instance or all of them due to issue on FiveM side?

It’s any Mastodon server which has enabled Authorized Fetch. So there could be a mix of those which do have it enabled and those which don’t. It’s not obvious to the user what the status of Authorized Fetch is on their instance. mas.to has since disabled Authorized Fetch (for different reasons!) so FiveM should now work again with our server.

**Comment by Legacy-TacticalGamingInteractive** [comment]
I tested it today with an instance that does not have Authorized Fetch enabled. No luck with that either. mas.to still does not work either. Still some kind of issue on FiveM side unfortunately. Not sure what exactly that is.

**Comment by Gogsi** [comment]
> I tested it today with an instance that does not have Authorized Fetch enabled. No luck with that either

The Mastodon fetch doesn't work on the browser version of https://servers.fivem.net regardless of Authorized Fetch, because of CORS issues. It used to be hidden because of that but with the recent refactor it was once again shown. Make sure you are testing in-game where CORS is disabled.
